### ISSUE TITLE
Documentation: Add some documentation for SaveComponent.gd

### ISSUE THREAD

**Issue by NightPotato** [chip003/starground-modding#6]
Currently the  `SaveComponent.gd` does have documentation of its usage. This might replace the need for #3 but we would need to know how it works and if it saves within the same `.dat` file. If it does save within there, I would still think that moving mod save data to its own system would be a good route to take.

**Comment by chip003** [comment]
Documentation for save_component.tscn has been created under the Components section in the wiki.
